baseURL = 'https://linonymous.in/'
languageCode = 'en-us'
title = 'The Towel'
theme = 'towel'
paginate = 10
enableRobotsTXT = true
enableGitInfo = true

[params]
  description = "I write, so that I may learn."
  author = "Linonymous"
  tagline = "I write, so that I may learn."
  twitter = "Iinonymous"
  github = "linonymous"

[permalinks]
  tech = '/tech/:slug/'
  dev-random = '/dev-random/:slug/'

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[markup]
  [markup.highlight]
    style = 'dracula'
    lineNos = false
    codeFences = true
    guessSyntax = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = 'Tech'
    url = '/tech/'
    weight = 1
  [[menu.main]]
    name = '/dev/random'
    url = '/dev-random/'
    weight = 2
  [[menu.main]]
    name = 'Books'
    url = '/books/'
    weight = 3
  [[menu.main]]
    name = 'About'
    url = '#'
    weight = 5
    identifier = 'about'
  [[menu.main]]
    name = 'Me'
    url = '/about/me/'
    weight = 1
    parent = 'about'
  [[menu.main]]
    name = 'Blog'
    url = '/about/blog/'
    weight = 2
    parent = 'about'

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

[sitemap]
  changefreq = 'weekly'
  priority = 0.5
